Fix alphabetize imports
angular/angular-cli pull request #17587
Opened 2020-04-30 13:34 UTC by timfrijtersppw

In this PR I've alphabetized some imports to avoid potential linting errors when generating files with angular-cli.

Also see:
https://palantir.github.io/tslint/rules/ordered-imports/

2020-11-21 00:12 UTC, gbumanzordev approved these changes

2020-11-25 10:23 UTC, timfrijtersppw commented
Updated the PR to master, all ci checks pass. I only don't know how to add the PR target label to this PR. Anyone an idea?

2020-11-25 14:53 UTC, clydin requested changes

2020-11-25 14:53 UTC, clydin commented on packages/schematics/angular/application/files/src/test.ts.template
> +import 'zone.js/dist/zone-testing';
This is a side effect inducing import that affects global state and should be first.  Can you revert this change?

2020-11-25 14:55 UTC, clydin requested changes
Please also change the commit message scope to `@schematics/angular`.

2020-11-25 15:09 UTC, timfrijtersppw commented
Changed the commit message scopes & reverted the test.ts change

2020-11-25 15:10 UTC, clydin commented
Looks like there's an accidental `.` in the commit scope.  Otherwise, LGTM.

2020-11-25 15:12 UTC, timfrijtersppw commented
> Looks like there's an accidental `.` in the commit scope. Otherwise, LGTM.

Wups, my bad. Renamed the commit message again 😄

2020-11-25 15:13 UTC, clydin approved these changes

2020-12-01 09:05 UTC, merged