refactor(@angular-devkit/schematics): change the order of node types in package.json template
angular/angular-cli pull request #18661
Opened 2020-08-30 15:47 UTC by bampakoa

Re-arrange the node types npm package so that `devDependencies` are sorted in  alphabetical order

2020-08-30 16:09 UTC, alan-agius4 requested changes
Thanks for this, however this changes the semantics because now `@types/jasmine` and `@types/jasminewd2` are included when `minimal` is true.

Also commit message scope is not correct as it should be `@schematics/angular`

2020-08-30 16:28 UTC, bampakoa commented
Thanks for the feedback @alan-agius4 . I have made some adjustments to the committed code along with the change in the message scope. I tried also to run the test suite with `yarn test --full` but yarn complained that it did not find the test command. Any thoughts on that?

2020-08-31 07:45 UTC, alan-agius4 commented
Thanks for this. Yeah to run the unit tests of `@schematics/angular` you need to run `yarn bazel test //packages/schematics/angular:angular_test `

2020-08-31 07:46 UTC, alan-agius4 approved these changes

2020-08-31 10:57 UTC, merged