Replace regex with correct project name valdiation
angular/angular-cli pull request #18831
Opened 2020-09-20 17:50 UTC by Jefiozie

If I understand the comments of @alan-agius4 on #17579 correct this PR will fix the IDE validation error that it is providing today.
I've replaced the regex with the correct one, just to make sure we are not forgetting when closing the ticket there is a second comment by @alan-agius4:

>When it comes to project directories, I am inclined towards always dasherizing the project folder name to align with other schematics where the folder name is always dasherized, that being said It's not a biggy, as long as the schema validation is fixed.

Should we make a separate issue for this or are we leaving this as is?

Let me know if I need to make changes or add additional information.

Closes #17579

2020-09-21 17:24 UTC, alan-agius4 requested changes
Thanks for this. 

Can you please update the commit message to match our guidelines in: https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#commit

Example
```
fix(@angular/cli): replace regex with correct project name validation

Closes #17579
```

2020-09-21 17:25 UTC, alan-agius4 commented
> If I understand the comments of @alan-agius4 on #17579 correct this PR will fix the IDE validation error that it is providing today.
> I've replaced the regex with the correct one, just to make sure we are not forgetting when closing the ticket there is a second comment by @alan-agius4:
> 
> > When it comes to project directories, I am inclined towards always dasherizing the project folder name to align with other schematics where the folder name is always dasherized, that being said It's not a biggy, as long as the schema validation is fixed.
> 
> Should we make a separate issue for this or are we leaving this as is?
> 
> Let me know if I need to make changes or add additional information.
> 
> Closes #17579

I think for the time being we can leave this as is.

2020-09-21 18:34 UTC, Jefiozie commented
Hi @alan-agius4, yes I wil do this first thing tomorrow.

2020-09-22 05:25 UTC, Jefiozie commented
Hi @alan-agius4, Í've made the changes as requested.

2020-09-22 08:16 UTC, alan-agius4 commented on packages/schematics/angular/application/index.ts
> +    const sourceDir = `${strings.dasherize(appDir)}/src/app`;
```suggestion
    const sourceDir = `$(appDir}/src/app`;
```

Shouldn't be needed, since it's already transformed in the above line.

2020-09-22 08:16 UTC, alan-agius4 commented on packages/schematics/angular/application/index_spec.ts
> +    expect(exists).toBeTruthy();
```suggestion
    expect(exists).toBeTrue();
```

2020-09-22 08:17 UTC, alan-agius4 commented on packages/schematics/angular/application/index_spec.ts
> +    expect(exists).toBeTruthy();
```suggestion
    expect(exists).toBeTrue();
```

2020-09-22 10:00 UTC, alan-agius4 approved these changes

2020-09-23 21:04 UTC, merged