feat(@schematics/angular): add generation for resolvers
angular/angular-cli pull request #19048
Opened 2020-10-11 17:11 UTC by Jefiozie

This will add the `resolvers` as an option to generate. 
You can use it by `ng g r <name> ` or `ng generate resolver <name> `  

closes: #17569

2020-10-12 10:42 UTC, Jefiozie commented
Just referencing @alan-agius4 or @clydin for reviewing 😄

2020-10-12 17:57 UTC, alan-agius4 requested changes
Thanks for this, one small NIT.

2020-10-12 17:57 UTC, alan-agius4 commented on packages/schematics/angular/resolver/schema.json
> +    "lintFix": {
Since this is a new schematic, can we not include the deprecated options please?

2020-10-12 17:57 UTC, alan-agius4 commented on packages/schematics/angular/resolver/index.ts
> +      options.lintFix ? applyLintFix(options.path) : noop(),
```suggestion
```

2020-10-12 17:57 UTC, alan-agius4 commented on packages/schematics/angular/resolver/index.ts
> +import { applyLintFix } from '../utility/lint-fix';
```suggestion
```

2020-10-13 16:09 UTC, alan-agius4 commented on packages/schematics/angular/resolver/schema.json
> +  "id": "SchematicsAngularresolver",
```suggestion
  "id": "SchematicsAngularResolver",
```

2020-10-13 16:33 UTC, Jefiozie commented
Will make these changes as soon as i have some time.

2020-10-14 05:51 UTC, Jefiozie commented
Hey @alan-agius4, I have changed your comments, I think it is good to do a quick review again. Thanks for your comments.

2020-10-14 14:40 UTC, alan-agius4 approved these changes

2020-10-14 17:26 UTC, alan-agius4 commented
Thanks for your contribution @Jefiozie.

2020-10-14 18:01 UTC, Jefiozie commented
Thank you, hope to do some more contributions.

2020-10-15 05:37 UTC, merged