chore(@angular-devkit/build-angular): `ng extract-i18n` support json
angular/angular-cli pull request #19701
Opened 2020-12-31 10:20 UTC by wenqi73

`@angular/localize` supports extracting as `json` file, but CLI does not support this.

2020-12-31 10:23 UTC, wenqi73 commented
@googlebot I fixed it.

2020-12-31 10:43 UTC, petebacondarwin commented
If you are extracting to JSON then surely you will need to implement merging translations stored in JSON too? See https://github.com/angular/angular/blob/master/packages/localize/src/tools/src/translate/translation_files/translation_parsers/simple_json_translation_parser.ts
Also, we recently implemented ARB format, which is another form of JSON that might be worth supporting: https://github.com/angular/angular/blob/master/packages/localize/src/tools/src/extract/translation_files/arb_translation_serializer.ts and https://github.com/angular/angular/blob/master/packages/localize/src/tools/src/translate/translation_files/translation_parsers/arb_translation_parser.ts

2021-01-05 03:35 UTC, wenqi73 commented
@petebacondarwin What do you mean by "implement merging translations"? Could you tell me the details?

2021-01-05 09:27 UTC, petebacondarwin commented
@wenqi73 - there are two main processes in i18n: extraction and merging (sometimes called translation or inlining). The extraction process involves parsing the code for `$localize` calls and rendering translation files (e.g. XLIFF) containing all the i18n messages. The merging process involves parsing the code for `$localize` calls and replacing those calls with translated messages, where the translated messages are read in from translation files (e.g. XLIFF).

When supporting a particular translation file format, we need to provide a serializer (used when extracting) and a parser (used when merging).

2021-01-05 09:45 UTC, wenqi73 commented
@petebacondarwin It already has the JSON parser in cli, https://github.com/angular/angular-cli/blob/97aa1fb7cc7595ca696fbe72fdf4982dd9815dfd/packages/angular_devkit/build_angular/src/utils/load-translations.ts#L69 so just need to add serializer? And now in my project I also use JSON files as translation files with `localize-extract`, it works fine!

2021-01-05 10:00 UTC, petebacondarwin commented
Gadzooks! You are right! I didn't see that. Nice. OK so you are good just to add the serializer. Sorry for the noise.

2021-01-05 12:40 UTC, wenqi73 commented
@petebacondarwin I have added arb format, please have a look😄

2021-01-05 12:44 UTC, petebacondarwin approved these changes
LGTM

2021-01-05 17:15 UTC, clydin requested changes
Can you also add an E2E test file for each of the formats?
You can use the following test file as a base (and the new tests can be placed in the same directory):
https://github.com/angular/angular-cli/blob/cfb368408b532e488acaa1a5a921240f0dc7dfad/tests/legacy-cli/e2e/tests/i18n/ivy-localize-dl-xmb.ts

2021-01-06 15:16 UTC, clydin reviewed
Code changes look good.
Can you re-structure the commits so that the PR contains two feature commits: one for JSON and one for ARB (with the tests for each included in their respective commits)?

With that adjustment this should be good to be merged.
Thank you for the contribution.

2021-01-07 08:06 UTC, wenqi73 commented
@clydin Commits have been readjusted.

2021-01-07 15:56 UTC, clydin commented on tests/legacy-cli/e2e/tests/i18n/ivy-localize-dl-json.ts
> +  await setupI18nConfig(true, 'xmb');
```suggestion
  await setupI18nConfig(true, 'json');
```

2021-01-08 08:37 UTC, wenqi73 commented on tests/legacy-cli/e2e/tests/i18n/legacy.ts
> +  if (format !== 'json') {
@clydin @petebacondarwin The message description will not be extracted into JSON files.

2021-01-08 19:15 UTC, clydin approved these changes
LGTM.

Thanks again for the contribution.

2021-01-08 19:45 UTC, merged