wip! prod mode by defaulta
angular/angular-cli pull request #20128
Opened 2021-02-24 08:52 UTC by alan-agius4

2021-02-27 13:51 UTC, destus90 commented
@alan-agius4 
Shouldn't be added a separator `--` after `npm run build` in order to pass additional options? I guess 
`npm run buid -- --watch --configuration development`

2021-02-27 15:06 UTC, alan-agius4 commented
@destus90, yeah indeed, thanks for pointing that out.

2021-03-09 10:15 UTC, alan-agius4 commented
@googlebot ping!

2021-03-09 15:27 UTC, clydin requested changes

2021-03-09 15:27 UTC, clydin commented on packages/schematics/angular/universal/index.ts
> +      const buildConfigurations = clientProject.targets.get('build')?.configurations;
```suggestion
      const buildConfigurations = buildTarget?.configurations;
```

2021-03-09 15:27 UTC, clydin commented on tests/legacy-cli/e2e/tests/build/lazy-load-syntax.ts
> +    buildTarget['options']['aot'] = true;
Duplicate statement?

2021-03-09 15:27 UTC, clydin commented on tests/legacy-cli/e2e/tests/build/multiple-configs.ts
> +  await ng('build', '--configuration=one,two,three', '--vendor-chunk=false');
The comment above should probably be changed as well since `--prod` is not at the end anymore.

2021-03-09 15:38 UTC, alan-agius4 commented on packages/schematics/angular/app-shell/index.ts
> +  return (host, content) => {
oops

2021-03-09 16:27 UTC, clydin approved these changes

2021-03-10 14:16 UTC, merged