fix(@angular/cli): Support XDG Base Directory Specfication
angular/angular-cli pull request #20556
Opened 2021-04-17 08:52 UTC by joshuachp

Reading throw  #16034 the angular config should be placed in the `$XDG_CONFIG_HOME/angular/` directory, but if the environmental variable $XDG_CONFIG_HOME is set the first check in the `xdgConfigHome` function will only put it in `$XDG_CONFIG_HOME` instead of the `angular/` directory.

Also renamed the config file from `.angular-config.json` to `config.json`  when it is in the `~/.config/angular/` directory since it doesn't need to be hidden.

2021-04-17 08:56 UTC, joshuachp commented
@googlebot I signed it!

2021-04-19 16:03 UTC, clydin requested changes
Thank you for the contribution.
It does appear this new behavior is correct based on the underlying specification.
However, since this would break existing users, both scenarios would need to be temporarily supported (two major versions is the typical timeframe). The older configuration location should also be converted to the new location to _fix_ existing cases.
Could you update the PR with the above support for existing users?

2021-04-19 17:54 UTC, joshuachp commented
I re added support for the old file locations.
Should I now automatically move the old files to the new location or is better to just print a warning to the user?

2021-04-26 18:59 UTC, clydin commented
I think a warning would suffice in this case.

2021-04-27 14:34 UTC, clydin commented on packages/angular/cli/utilities/config.ts
> +import { join, json, workspaces } from '@angular-devkit/core';
The `join` addition here appears unused.

2021-04-28 07:28 UTC, joshuachp commented
I added the warning using `console.warn`, since it seems overwritten in the index file by the logger.

2021-04-28 13:52 UTC, clydin approved these changes
LGTM.
Thank you for the contribution.

2021-04-28 14:36 UTC, merged