Enum schematic fix
angular/angular-cli pull request #20670
Opened 2021-04-30 13:16 UTC by mephistorine

2021-04-30 17:07 UTC, alan-agius4 requested changes
Thanks for this.

Couple of things

- Can you please drop the first commit?
- Kindly use `@schematics/angular` as commit message scope.
- Add `closes: #20667` as commit message footer.

2021-05-01 19:54 UTC, mephistorine commented
@alan-agius4 thanks, ok.

2021-05-01 20:33 UTC, alan-agius4 approved these changes

2021-05-01 20:33 UTC, alan-agius4 commented on packages/schematics/angular/enum/index.ts
> +    options.type = !!options.type ? `.${options.type}` : '';
nit
```suggestion
    options.type = options.type ? `.${options.type}` : '';
```

2021-05-01 20:34 UTC, alan-agius4 commented on packages/schematics/angular/enum/schema.json
> +      "default": ""
nit 
```suggestion
```

2021-05-01 20:48 UTC, mephistorine commented on packages/schematics/angular/enum/index.ts
> +    options.type = !!options.type ? `.${options.type}` : '';
done 👍🏻

2021-05-01 20:48 UTC, mephistorine commented on packages/schematics/angular/enum/schema.json
> +      "default": ""
done 👍🏻

2021-05-01 21:02 UTC, alan-agius4 approved these changes
LGTM, thanks for your contribution.

Can you kindly squash the commits? Thanks.

2021-05-01 21:04 UTC, mephistorine commented
@alan-agius4 yes, give a second. :)

2021-05-01 21:16 UTC, alan-agius4 approved these changes
LGTM, thanks

2021-05-01 21:17 UTC, mephistorine commented
@alan-agius4 Thanks a lot 😃

2021-05-03 14:43 UTC, merged