Fix for webpack 5 + babel "failed to resolve" error
angular/angular-cli pull request #20810
Opened 2021-05-15 21:55 UTC by buu700

Addresses #20800.

I don't know if this is the best fix for this issue, but seems to be an effective temporary workaround at least. It's possible that a bug may need to be fixed in `babel-loader` or `@babel/runtime`.

2021-05-15 22:09 UTC, buu700 commented
@googlebot I signed it!

2021-05-16 13:29 UTC, dangrussell approved these changes
This solves the issue for me!

2021-05-17 06:14 UTC, alan-agius4 commented on packages/angular_devkit/build_angular/src/webpack/configs/common.ts
> +          resolve: {fullySpecified: false},
```suggestion
          // The below is needed due to a bug in `@babel/runtime`. See: https://github.com/babel/babel/issues/12824
          resolve: {fullySpecified: false},
```

Let's add a comment explaining why this is needed.

2021-05-17 06:15 UTC, alan-agius4 requested changes
Hi @buu700, 

Can you please fix the validation CI by updating your commit to;
```
fix(@angular-devkit/build-angular): correctly resolve babel runtime helpers

Closes #20800
```

2021-05-17 17:23 UTC, buu700 commented
Done, thanks @alan-agius4!

2021-05-17 17:36 UTC, alan-agius4 approved these changes
Thanks LGTM

2021-05-18 05:08 UTC, merged