fix(angular_devkit): Update postcss dependency to 8.2.15
angular/angular-cli pull request #20874
Opened 2021-05-20 18:00 UTC by jcesarmobile

I'm having problems installing "@angular-devkit/build-angular": "~0.1102.13" because it uses postcss 8.2.14, but also cssnano 5.0.2, which uses  cssnano-preset-default@5.1.0, which has a peer dependency to postcss@"^8.2.15", so npm 7 fails to install because of peer dependency mismatch

2021-05-20 18:03 UTC, jcesarmobile commented
@googlebot I signed it!

2021-05-20 18:58 UTC, naderalfakesh approved these changes

2021-05-20 18:58 UTC, dogandipcin approved these changes

2021-05-21 10:22 UTC, alan-agius4 requested changes
Thanks for your contribution, but there needs to be some changes to be able to land this PR.

- Can you please update the commit message as per our [guidelines](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#commit)?
- Update the version `postcss` in the root `package.json` and update also `yarn.lock` file

2021-05-21 11:11 UTC, jcesarmobile commented
I did it from github site, so can't make those changes, sorry, just wanted to unblock all the people that can't install this package on npm 7.

2021-05-21 11:11 UTC, closed without merging