refactor: fix ng-new template pointing to Angular animations with Material logo
angular/angular-cli pull request #22103
Opened 2021-11-05 14:05 UTC by devversion

Fixes that the `new new` generated app component template currently
provides a link to Angular Animations with the Angular Material logo,
according to: https://angular.io/presskit.

This commit switches the link to Angular Material with the assumption
that this was intended to point to Angular Material from the
beginning.

![tempsnip](https://user-images.githubusercontent.com/4987015/140523060-57bfcfbb-d812-4533-8ecd-3cfb448abb50.png)

2021-11-05 14:17 UTC, alan-agius4 approved these changes

2021-11-05 15:58 UTC, twerske requested changes
Since Angular Material is already in the above section, can we change this logo to the Animations logo from https://angular.io/presskit#animations instead?

2021-11-09 14:24 UTC, devversion commented
@twerske Updated as per offline discssion (removal of the CLI and Material icons below; and just having Angular Material above in the useful links section). Here is a screenshot and a test-app:

![image](https://user-images.githubusercontent.com/4987015/140941057-7c58e207-4a7a-4bd7-b9da-3c936f1c9d44.png)

https://stackblitz.com/edit/angular-g8empx?file=src%2Fapp%2Fautocomplete-auto-active-first-option-example.html 

Note that I just took the Angular Material logo and turned it gray to match up with the other icons.

2021-11-09 17:59 UTC, twerske approved these changes
LGTM - thank you!

2021-11-09 18:01 UTC, alan-agius4 approved these changes

2021-11-10 14:50 UTC, merged