feat(@schematics/angular): add environments generation schematic
angular/angular-cli pull request #24409
Opened 2022-12-09 23:53 UTC by clydin

A schematic has been added that will allow the generation of environment files for all existing build configurations within a project. The `fileReplacements` option will also be setup to allow the replacement of the appropriate environment file. Environment files themselves do not provide any special behavior beyond that of other application TypeScript files and rely on the `fileReplacements` option for build-time behavior. The schematic will skip generating environment files for configurations that already have an appropriately named environment file. The `fileReplacements` option addition will also be skipped if an appropriate entry is already present.

Closes #24381

2022-12-12 09:00 UTC, alan-agius4 requested changes
Couple of comments. Otherwise this looks good.

2022-12-12 09:00 UTC, alan-agius4 commented on packages/schematics/angular/environments/index.ts
> +    const project = workspace.projects.get(options.project);
Can you add a validation that checks that these are being added to the correct project type (ie: application)?

2022-12-12 09:00 UTC, alan-agius4 commented on packages/schematics/angular/environments/index.ts
> +    const buildTarget = project.targets.get('build');
Can you also add the same thing for `server` target? It's important that the file replacements are added to both.

2022-12-12 09:00 UTC, alan-agius4 commented on packages/schematics/angular/environments/schema.json
> +  "title": "Angular e2e Application Options Schema",
```suggestion
  "title": "Angular Environment Options Schema",
```

2022-12-13 09:31 UTC, alan-agius4 approved these changes

2022-12-13 14:27 UTC, merged

2022-12-14 14:54 UTC, clydin commented
Description updated with an example usage.

2022-12-31 21:37 UTC, ek1mb4 commented
> A schematic has been added that will allow the generation of environment files for all existing build configurations within a project. The `fileReplacements` option will also be setup to allow the replacement of the appropriate environment file. Environment files themselves do not provide any special behavior beyond that of other application TypeScript files and rely on the `fileReplacements` option for build-time behavior. The schematic will skip generating environment files for configurations that already have an appropriately named environment file. The `fileReplacements` option addition will also be skipped if an appropriate entry is already present. Example usage: `ng generate environments`
> 
> Closes #24381

Your example does not work. "ng generate environments"

2023-01-03 17:44 UTC, arambazamba commented
@clydin Great job … For simpler apps environment.ts and *.prod.ts was a good & simple solution to provide global vars like api url, … thanks a lot 👍

2023-02-02 03:17 UTC, cosmoKenney commented
Somewhere along the line whole environments thing stopped working. In angular 8 I used to have one for development, staging and production. And had corresponding fileReplacements in angular.json. Doing ng build --configuration=staging would copy the environment.staging.ts into the dist/environments/environment.ts file. That no longer works in Angular 14. How do I accomplish the same thing with Angular 14?