fix(@angular-devkit/build-angular): support CSP on critical CSS link tags
angular/angular-cli pull request #24903
Opened 2023-03-24 11:04 UTC by crisbeto

Based on https://github.com/angular/angular-cli/pull/24880#pullrequestreview-1347993316. Critters can generate `link` tags with inline `onload` handlers which breaks CSP. These changes update the style nonce processor to remove the `onload` handlers and replicate the behavior with an inline `script` tag that gets the proper nonce.

Note that earlier we talked about doing this through Critters which while possible, would still require a custom HTML processor, because we need to both add and remove attributes from an element.

2023-03-24 12:18 UTC, crisbeto commented on packages/angular_devkit/build_angular/src/utils/index-file/style-nonce.ts
> +(function() {
I wrote this ES5 just in case, but it can be easily converted to ES2015+.

2023-03-24 13:31 UTC, alan-agius4 requested changes
As discussed previously in the previous [PR](https://github.com/angular/angular-cli/pull/24880#pullrequestreview-1347993316), IMHO, this is not the write place to do such changes.  I was fine in doing the nonce as part of the index plugin to handle all the style tags, but in this case the `link[onload]` is specific to critical CSS Inlining which is used also in app-shell, and universal where the index html augmenter is not run as such currently `nonce` attribute is not added.

The correct place to do this would be the `ExtendedCritters`, until it's properly support by `Critters` proper, which is highly unlikely to happen any time soon. Doing the logic in ExtendedCritters would cover all the use-cases and can easily be ported over to the universal repo which does not have support for the nonce attribute yet. Adding this logic here only solves 1 out of the 4 use-cases (CSR, SSR, SSG and App-Shell). We cannot ignore the other use-cases and just focus on one.

To fix this across the board is simpler than you might think, as in `ExtendedCritters` you can access the `document` so there is not need to re-parse the HTML. What needs to be done is to override the `embedLinkedStylesheet` method https://github.com/GoogleChromeLabs/critters/blob/a590c05f9197b656d2aeaae9369df2483c26b072/packages/critters/src/index.js#L311, where the document can be queried to get the `nonce` value, add it to the `style` element and inject the `link` tag and `onload` handler script.

Eventually It would also be great if you can add some nonce tests in https://github.com/angular/angular-cli/blob/main/packages/angular_devkit/build_angular/src/builders/app-shell/app-shell_spec.ts 

Happy to help if needed.

2023-03-24 15:48 UTC, crisbeto commented
@alan-agius4 I've moved the logic into the `CrittersExtended`, but I had to do a hacky workaround to override `embedLinkedStylesheet` since it isn't part of the Critters typings.

2023-03-27 14:59 UTC, alan-agius4 requested changes

2023-03-27 15:05 UTC, crisbeto commented on packages/angular_devkit/build_angular/src/utils/index-file/inline-critical-css.ts
> +        `  function onLoad() {this.media = this.getAttribute('${CSP_MEDIA_ATTR}');}`,
We know that the link tags will be direct children of the `head` so we don't have to traverse the entire document.

2023-03-27 15:08 UTC, crisbeto commented on packages/angular_devkit/build_angular/src/utils/index-file/inline-critical-css.ts
> +  private embedLinkedStylesheetOverride: EmbedLinkedStylesheetFn = async (link, document) => {
In what case does the `style` tag get produced then? I didn't see any other unit tests checking for the style tags.

2023-03-27 17:20 UTC, alan-agius4 commented on packages/angular_devkit/build_angular/src/utils/index-file/inline-critical-css.ts
> +        `  function onLoad() {this.media = this.getAttribute('${CSP_MEDIA_ATTR}');}`,
I led my why not simply use a query selector? 

To only visit the children of head, you can use `document.head.querySelectorAll`

2023-03-27 17:22 UTC, alan-agius4 commented on packages/angular_devkit/build_angular/src/utils/index-file/inline-critical-css.ts
> +  private embedLinkedStylesheetOverride: EmbedLinkedStylesheetFn = async (link, document) => {
The style tag get produced by critters outside of the index augmentation phase in app-shell.  Add an integration test in https://github.com/angular/angular-cli/blob/0ac5f271462524bb0f05045d47d2a1a76c40f22a/packages/angular_devkit/build_angular/src/builders/app-shell/app-shell_spec.ts#L145

2023-03-27 17:40 UTC, crisbeto commented on packages/angular_devkit/build_angular/src/utils/index-file/inline-critical-css.ts
> +        `  function onLoad() {this.media = this.getAttribute('${CSP_MEDIA_ATTR}');}`,
querySelectorAll will visit all descendants, not just the direct children. The selector can be tweaked only to visit direct children as well, but I think that it's still more overhead compared to checking the children directly.

2023-03-27 17:44 UTC, alan-agius4 commented on packages/angular_devkit/build_angular/src/utils/index-file/inline-critical-css.ts
> +        `  function onLoad() {this.media = this.getAttribute('${CSP_MEDIA_ATTR}');}`,
Thanks for the explanation. In that case, one little nit, can we change the syntax to ES6+?

2023-03-28 07:49 UTC, crisbeto commented on packages/angular_devkit/build_angular/src/utils/index-file/inline-critical-css.ts
> +  private embedLinkedStylesheetOverride: EmbedLinkedStylesheetFn = async (link, document) => {
Done, although I ended up just iterating over all `<style>` tags in the `document.head`. This seemed like a lot of logic to duplicate from Critters.

2023-03-28 11:20 UTC, alan-agius4 approved these changes

2023-03-28 14:45 UTC, merged