refactor(@angular/ssr): rename SSR port env variable
angular/angular-cli pull request #27333
Opened 2024-03-21 21:01 UTC by 9kubczas4

Rename SSR port env variable to SSR_PORT.

## PR Checklist

Please check to confirm your PR fulfills the following requirements:

- [ x] The commit message follows our guidelines: https://github.com/angular/angular-cli/blob/main/CONTRIBUTING.md#-commit-message-guidelines
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [x ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

## Does this PR introduce a breaking change?

- [ ] Yes
- [ x] No

## Other information

2024-03-22 07:30 UTC, alan-agius4 requested changes
Can you also please add more context in the commit body? Example: 
Linking to https://github.com/firebase/firebase-tools/issues/6651#issuecomment-1881647322 and explaining that `PORT` is reserved variable as per https://firebase.google.com/docs/functions/config-env?gen=2nd#reserved-names?

Additionally the scope should be `@schematics/angular`.

2024-03-22 07:30 UTC, alan-agius4 commented on packages/angular_devkit/build_angular/src/builders/ssr-dev-server/index.ts
> +  const env = { ...process.env, SSR_PORT: '' + port };
In the dev-server we need to support both for backwards computability. 

```suggestion
  const env = { ...process.env, SSR_PORT: '' + port, PORT: '' + port };
```

2024-03-22 16:46 UTC, alan-agius4 approved these changes

2024-03-22 17:23 UTC, merged

2024-04-02 14:48 UTC, inlined commented
This actually _breaks_ Firebase on deploy. PORT is a reserved variable because it's what Functions and Run uses to set the port to listen to. Let's collaborate on a working solution.

2024-04-02 14:57 UTC, alan-agius4 commented
@inlined, should we revert this?