build: update to TypeScript 5.7
angular/angular-cli pull request #28992
Opened 2024-11-28 15:34 UTC by crisbeto

Updates the repo to use TypeScript 5.7.

2024-11-29 11:54 UTC, alan-agius4 commented on packages/schematics/angular/utility/latest-versions/package.json
> +    "ng-packagr": "^19.1.0-next.1",
This should be `.0` otherwise the prerelease check will fail.

```suggestion
    "ng-packagr": "^19.1.0-next.0",
```

2024-12-02 09:57 UTC, alan-agius4 requested changes
These peer dependencies are not valid. 

The string value need to be an **exact** match to `^19.0.0 || ^19.1.0-next.0`, any other value is not valid and will cause the release checks to fail.

I have a PR to bump the packages https://github.com/angular/angular-cli/pull/29007

2024-12-02 10:02 UTC, crisbeto commented
This won't allow any other 19.0.x versions though (e.g. 19.0.1). I think the right thing to do is to require only 19.1.x in the next minor.

2024-12-02 12:21 UTC, alan-agius4 commented
Sorry I was meant to be `^19.0.0 || ^19.1.0-next.0`

2024-12-02 12:41 UTC, alan-agius4 reviewed
Looks like there are a couple of places where typescript has not been updated.

```
packages/angular_devkit/schematics_cli/blank/project-files/package.json
packages/angular_devkit/schematics_cli/schematic/files/package.json
```

2024-12-02 12:41 UTC, alan-agius4 commented on packages/angular_devkit/build_angular/test/hello-world-lib/projects/lib/package.json
>    "name": "lib",
Kindly revert this, this is a test file.

2024-12-02 12:41 UTC, alan-agius4 commented on packages/schematics/angular/utility/latest-versions/package.json
> +    "ng-packagr": "^19.1.0-next.2",
This needs to be `.0`. 

All framework and ng-packagr versions must be `^19.1.0-next.0` during the prerelease phase any other value is not allowed. 

```suggestion
    "ng-packagr": "^19.1.0-next.0",
```

2024-12-02 12:55 UTC, crisbeto commented
Should be ready to go now.

2024-12-02 12:56 UTC, alan-agius4 approved these changes

2024-12-02 13:15 UTC, merged